name: Flutter Web
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - name: Create temporary service account file
        run: |
          echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json
      - name: Build Web
        run: |
          flutter build web --dart-define=SERVICE_ACCOUNT_FILE=service_account.json
      - name: Remove temporary service account file
        run: rm service_account.json
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./build/web